### ISSUE TITLE
IndexOtOfRange in MinHeap

### ISSUE THREAD

**Issue by nezix** [ArthurBrussee/KNN#2]
I found a bug when trying to get point cloud neighbors of mesh vertices.
I join a script that parses a file and compute the neighbor search to this issue.

Error generated is:

> IndexOutOfRangeException: Index 5 is out of range of '5' Length.
Unity.Collections.NativeArray`1[T].FailOutOfRangeError (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:208)
Unity.Collections.NativeArray`1[T].CheckElementWriteAccess (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:127)
Unity.Collections.NativeArray`1[T].set_Item (System.Int32 index, T value) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:146)
KNN.Internal.MinHeap.PushObj (KNN.Internal.KdQueryNode obj, System.Single h) (at C:/Users/Xavier/Dev/KNN/MinHeap.cs:118)
KNN.KnnContainer.PushToHeap (System.Int32 nodeIndex, Unity.Mathematics.float3 tempClosestPoint, Unity.Mathematics.float3 queryPosition, KNN.KnnContainer+KnnQueryTemp& temp) (at C:/Users/Xavier/Dev/KNN/KnnContainer.cs:449)
KNN.KnnContainer.KNearest (Unity.Mathematics.float3 queryPosition, Unity.Collections.NativeSlice`1[T] result, KNN.KnnContainer+KnnQueryTemp& temp) (at C:/Users/Xavier/Dev/KNN/KnnContainer.cs:500)
KNN.Jobs.KNearestBatchQueryJob.Execute (System.Int32 startIndex, System.Int32 count) (at C:/Users/Xavier/Dev/KNN/KnnJobs.cs:61)
Unity.Jobs.IJobParallelForBatchExtensions+ParallelForBatchJobStruct`1[T].Execute (T& jobData, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) (at Library/PackageCache/com.unity.jobs@0.1.1-preview/Unity.Jobs/IJobParallelForBatch.cs:82)

[bugMinHeap_outofrange.zip](https://github.com/ArthurBrussee/KNN/files/3554576/bugMinHeap_outofrange.zip)

**Comment by nezix** [comment]
This only occurs when searching for 1 neighbor.

**Comment by ArthurBrussee** [comment]
Thanks for the detailed bug report! Was able to repro and fix.

Problem was that I was sizing some stack incorrectly based on K. It's properly sized now and fixes the out of index error
